### ISSUE TITLE
OC使用SDK并且  pod 'IQKeyboardManager',会导致所有编辑框点击闪退

### ISSUE THREAD

**Issue by 19aneng** [ECPay/ECPayPaymentGatewayKit_iOS#2]
pod 'IQKeyboardManager'
  pod 'ECPayPaymentGatewayKit', '~> 1.3.2'

**Comment by yen064** [comment]
Please remove pod IQKeyboardManager(objective-c version)
and add IQKeyboardManager for swift version, thanks.

Example in Podfile:

<strike>pod 'IQKeyboardManager'</strike>
pod 'IQKeyboardManagerSwift'
